# Generated by Django 5.1.4 on 2025-01-28 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Visit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cif', models.CharField(max_length=100)),
                ('contract_number', models.CharField(max_length=100)),
                ('address', models.TextField()),
                ('borrower', models.CharField(max_length=200)),
                ('location', models.CharField(max_length=200)),
                ('region', models.CharField(max_length=100)),
                ('region_manager', models.CharField(max_length=100)),
                ('responsible_person', models.CharField(max_length=100)),
                ('contact_type', models.CharField(max_length=100)),
                ('contact_person', models.CharField(max_length=100)),
                ('meeting_place', models.CharField(max_length=200)),
                ('notes', models.TextField(blank=True, null=True)),
                ('employee_name', models.CharField(max_length=100)),
                ('travel_date', models.DateField()),
                ('month', models.CharField(max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('overdue_days', models.IntegerField()),
            ],
        ),
    ]
