# Generated by Django 5.1.4 on 2025-01-28 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visits', '0002_visit_latitude_visit_longitude_alter_visit_cif_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='visit',
            name='is_sent',
            field=models.BooleanField(default=False),
        ),
    ]
